import type { Metadata } from "next";
import { Montserrat, Anton  } from 'next/font/google'

import "./globals.css";

const montserrat = Montserrat({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-montserrat"
})

const anton = Anton({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-anton",
  weight: "400"
})

export const metadata: Metadata = {
  title: "Gata Preta Sapatilhas",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} ${anton.variable} antialiased font-montserrat`}
        >
        {children}
      </body>
    </html>
  );
}
